### ISSUE TITLE
Exception thrown when comparing facts and unitRef is missing

### ISSUE THREAD

**Issue by dgm9704** [dgm9704/Xoxo#50]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Diwen.Xbrl.Fact.Equals(Fact other)
   at System.Collections.Generic.GenericEqualityComparer`1.Equals(T x, T y)
   at System.Collections.Generic.LinkedList`1.Find(T value)
   at Diwen.Xbrl.ListExtensions.ContentCompareReport[T](IList`1 left, IList`1 right)
   at Diwen.Xbrl.InstanceComparer.FactComparison(Instance a, Instance b)
   at Diwen.Xbrl.InstanceComparer.Report(Instance a, Instance b, ComparisonTypes comparisonTypes)
   at XbrlCompare.Program.CompareAndReport(String inputReport, String outputReport, String comparisonReport, ComparisonTypes comparisonTypes)
   at XbrlCompare.Program.Main(String[] args)

**Comment by dgm9704** [comment]
duplicate of #49
